spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost/Journal}
#    username: postgres
#    password: 123
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create